//This file is automatically generated by MATLAB, see createHeaderFile.m  or saveLDPCheader.m .

#ifndef QC_LDPC
#define QC_LDPC

//Values in bits:
#define N 1944 
#define K 1458 
#define M 486 

//WIMAX: Z divisible by 4,in (24, ..., 96 ) WIFI6:  Z in ( 27, 54, 81 )
#define Z 81 

//Values in blocks of bits of size Z:
#define NB 24 	// should be 24
#define KB 18 
#define MB 6 

//Model matrix assumed to be already scaled:
extern const int8_t HBM[ MB ][ NB ] ; 

//Encoder paramaters:
typedef uint8_t WORD ;
#define WB 8 		//word size in bits
#define WBE 3 		//WB exponent: WB == 2^WBE
#define ZW 10 		//Z in words
#define NW 243 		//must be integral multiple of ZW
#define MW 60.75 		//must be integral multiple of ZW
#define KW 182 		//must work together with MWF

#undef BITMAP 		//determines 'array' or 'bitmap' implementation

#ifdef BITMAP
	typedef WORD BLOCK[ ZW ] ;
#else
	typedef WORD BLOCK[ Z ] ;
#endif

typedef BLOCK *BLOCK_P ;


//Decoder parameters:
#define G_MAX 15 

#undef FIXED //determines floating point or fixed point decoder

typedef float FP ; 
#define FP_MAX FLT_MAX
#define N_TH 32 //nr. of decoder threads

//Definitions for MEX:

//Encoder:
#define UINTXY mxUint8 
#define UINTXY_CLASS mxUINT8_CLASS 
#define GET_UINTXY mxGetUint8s 


//Decoder:
#define FP_CLASS mxSINGLE_CLASS 
#define GET_FP mxGetSingles 


#endif

